name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Create a new builder
      run: |
        docker buildx create --use --name mybuilder --driver docker-container
        docker buildx inspect mybuilder --bootstrap

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/your-image:latest
          your-dockerhub-username/your-image:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
